# Generated by Django 5.1.6 on 2025-03-03 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_task_assigned_to_task_priority_alter_task_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='location_status',
            field=models.CharField(choices=[('in-house', 'In-House'), ('off-site', 'Off-Site')], default='in-house', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='cmms.equipment'),
        ),
    ]
