# Generated by Django 5.1.6 on 2025-03-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0003_alter_equipment_location_status_alter_part_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='equipment',
        ),
        migrations.AddField(
            model_name='part',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='parts', to='cmms.equipment'),
        ),
    ]
