# Generated by Django 5.1.6 on 2025-03-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0004_remove_part_equipment_part_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='part_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='supplied_parts', to='cmms.vendor'),
        ),
    ]
